DROP TABLE IF EXISTS photos     CASCADE;
DROP TABLE IF EXISTS waypoints  CASCADE;
DROP TABLE IF EXISTS events     CASCADE;
DROP TABLE IF EXISTS routes     CASCADE;
DROP TABLE IF EXISTS follows    CASCADE;
DROP TABLE IF EXISTS users      CASCADE;
DROP TYPE  IF EXISTS visibility_enum;
